// Generated by CodiumAI

describe('numberChecker', () => {

});

    // Test that the returned function from numberChecker returns the same result when called with the same number multiple times.
    it('should return the same result when called with the same number multiple times', () => {
      const arrNum = [1, 2, 3, 4, 5];
      const checkNumber = numberChecker(arrNum);
  
      expect(checkNumber(3)).toBe(true);
      expect(checkNumber(3)).toBe(true);
      expect(checkNumber(3)).toBe(true);
    });

